### ISSUE TITLE
Weird artifacts

### ISSUE THREAD

**Issue by kororro** [vpenades/MonoGame.AnimAndPBR#9]
I integrated this awesome library to my own engine and noticed some weird artifacts when moving camera around.
![Screenshot (18)](https://user-images.githubusercontent.com/42260382/99663186-e6b01280-2a6e-11eb-9e42-ebced1c92b15.png)

You can check it like this:
In Demo3, changed 2 lines:

    _Shark.WorldMatrix = Matrix.CreateTranslation(3, 0, -6);
and 
    var camPos = new Vector3(4, 2, 8);

**Comment by vpenades** [comment]
Although the library is able to load most glTFs, it doesn't protect you from malformed glTF models.

I noticed too, that the Shark is not being rendered correctly at times:  the reason is because it was exported with double sided face culling... which is wrong for models with volume... so there's not much that can be done on that aspect other than being careful and inspecting the assets before loading them.

Btw, it's great you're using the library, but keep in mind that it's still WIP, so lots of changes might happen on every update.

**Comment by kororro** [comment]
Ah now I understand. Tested and yes, when going inside shark, there is inside polys too. 

"Btw, it's great you're using the library, but keep in mind that it's still WIP, so lots of changes might happen on every update."
Actually Im using version before Scene3D and have modified it (and using latest shaders), so changes doesnt bother me :) 
I will update it when api is stable, if I need to.
